FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3001
ENV DATABASE_PATH=/data/shopping-list.db
ENV NODE_OPTIONS=--max-old-space-size=384

RUN apk add --no-cache dumb-init

COPY package*.json ./
COPY server/package*.json ./server/
COPY web/package*.json ./web/
COPY node_modules ./node_modules
COPY server/dist ./server/dist
COPY web/dist ./web/dist
COPY schema ./schema

VOLUME ["/data"]
EXPOSE 3001

CMD ["dumb-init", "node", "server/dist/index.js"]
